### ISSUE TITLE
Update Node Sass for Node 8

### ISSUE THREAD

**Issue by KrystofM** [manGoweb/mango-cli#155]
Update dependencies for newer version of Node Sass. When developing with mango-cli error occurs.

![18944663_1715254788503415_1923813122_n](https://user-images.githubusercontent.com/23424878/26841078-b7897dc0-4ae8-11e7-883e-5dfb2b8e6311.png)

From old version - 3.13.1 to newer version - 4.5.3, which supports Node 8.

![nodesassversion](https://user-images.githubusercontent.com/23424878/26841265-40e1c866-4ae9-11e7-9e5b-ef07c885e4e6.PNG)

Check if the change of major Node-Sass version does not brake anything.

**Comment by enzy** [comment]
There is always a slight delay with sub dependencies to catch up to the latest Node version. This problem is caused by `gulp-sass` which has not been updated yet.

In the meantime I recommend to install (nvm)[https://github.com/coreybutler/nvm-windows] and switch between node versions when you need to.

**Comment by KrystofM** [comment]
It´s actually a friends error that popped while he was trying mango-cli with Node 8. I presume other errors will unambiguously emerge from the update to v8. So I am doin well with v7 😃 But thanks for the recommendation :-)

**Comment by enzy** [comment]
Actually it works under Node 8 just fine, but you need to reinstall all dependencies after the upgrade. Comment if it's still relevant.
